name: docker_build_push_acr
on:
  push:
    branches:
      - "main"
   # tags:
   #   - 'v[0-9]+[0-9]+[0-9]'

 
jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
    environment: production
  
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
 
    - name: Build the frontend image and push it to ACR
      uses: docker/build-push-action@v2
      with:
        push: true
        #tags: lmspython.azurecr.io/lmspython:${{ github.sha }}
        tags: lmspython.azurecr.io/lmspython:v0.1.0
      # # tags: ${{ secrets.DOCKERHUB_USERNAME }}/123456789_dkr_ecr_us_east_1_amazonaws_com_nginx:1.25.3-alpine-slim 
        file: ./Dockerfile  
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: lmsrg
        dns-name-label: lmspythonwebsite
        image: lmspython.azurecr.io/lmspython:1.25.4-alpine-slim
        cpu: 1
        memory: 1
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        name: lmspythonwebsite
        location: 'eastus'